name: Auto CICD

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      moduleDir: ${{ steps.auto-ci.outputs.moduleDir}}
      info: ${{ steps.auto-ci.outputs.info}}
    steps:
      - uses: actions/checkout@v2
      - name: lambda-python-template
        uses: wangziling100/LambdaPythonAction@v1
        env:
          GITHUB_WORKSPACE: github_workspace
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          SAM_CLI_TELEMETRY: 0
  feedback:
    runs-on: ubuntu-latest
    if: needs.ci.outputs.info=='normal'||needs.ci.outputs.info=='publish'
    needs: ci
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1